// Keep role and status values aligned with the backend.

export const ROLES = Object.freeze({
  PASSENGER: 'PASSENGER',
  DRIVER: 'DRIVER',
})

export const RIDE_STATUS = Object.freeze({
  REQUESTED: 'REQUESTED',
  MATCHED: 'MATCHED',
  DRIVER_ARRIVED: 'DRIVER_ARRIVED',
  ONGOING: 'ONGOING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
})

export const RIDE_STATUS_ORDER = [
  RIDE_STATUS.REQUESTED,
  RIDE_STATUS.MATCHED,
  RIDE_STATUS.DRIVER_ARRIVED,
  RIDE_STATUS.ONGOING,
  RIDE_STATUS.COMPLETED,
]

export const CANCELLABLE_RIDE_STATUSES = [
  RIDE_STATUS.REQUESTED,
  RIDE_STATUS.MATCHED,
]

export const VEHICLE_STATUS = Object.freeze({
  ONLINE: 'ONLINE',
  OFFLINE: 'OFFLINE',
})

export const PAYMENT_METHODS = Object.freeze({
  CASH: 'CASH',
  TESLA_WALLET: 'TESLA_WALLET',
})

export const HISTORY_ACTIONS = [
  'REQUESTED',
  'ACCEPTED',
  'DRIVER_ARRIVED',
  'STARTED',
  'COMPLETED',
  'CANCELLED',
]